### ISSUE TITLE
文档里写了@SharedEvent注解可以监听事件，新版本没了？

### ISSUE THREAD

**Issue by monyuan** [halo-dev/rfcs#23]
“当 Halo 中标注了 @SharedEvent 注解的事件被发布时插件中可以使用同样的方式监听到”

这一段，如果要监听文章发布事件，该如何实现

**Comment by JohnNiang** [comment]
Hi @monyuan , 目前在 Halo core 中似乎没有对 [PostPublishedEvent](https://github.com/halo-dev/halo/blob/694ad26c3f1f076c0f5621ae11f1f69f5df2fd87/application/src/main/java/run/halo/app/event/post/PostPublishedEvent.java#L5) 标注注解 `@SharedEvent`。 可能无法正常在插件中监听该事件。
